### ISSUE TITLE
Create Fee wizard in Preferences

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#154]
Fees tab
Miners' fee
The current miners' fee is 1,000 satoshis per kB.

You can increase this fee which might get your transaction into a block faster 
Slider 1,000 to 10,000 with intervals of 1,000 satoshis.

Client fee
The current client fee is 1,000 satoshis per transaction sent. 
You currently owe XXX. Payable in Y sends.	

+ Ability to overpay BRIT if you like to avoid privacy issues.

**Comment by bitcoin-solutions** [comment]
Add the MultiBit donation address always to the list of BRIT addresses.
Add a panel to the Fee Preferences screen/ wizard making it easy for users to donate, explaining fees up to the donaiton amount are waived

**Comment by jim618** [comment]
This is working but still needs some code refactoring and FEST tests.
Screenshot:
![screen shot 2015-02-22 at 16 36 17](https://cloud.githubusercontent.com/assets/919427/6319342/25e9fe54-bab1-11e4-8bc4-8e3b9bfc95e4.png)

**Comment by gary-rowe** [comment]
Looking good! Will need the supporting text to explain the effect of moving the slider around and a summary of the client fees.

**Comment by jim618** [comment]
Updated screenshot with more explanatory help and a donate button (that fills out the Send screen directly for the user):

![screen shot 2015-02-23 at 12 12 17](https://cloud.githubusercontent.com/assets/919427/6327609/bdc9106c-bb55-11e4-9c9e-260b79152f7f.png)

**Comment by gary-rowe** [comment]
Looking good. Some UI suggestions:

* include the outstanding client fee balance and when it comes due (replicate the Send confirmation panel info) since this is essentially a dashboard view
* Change "Default" to 1000sat since we know that is sensible (perhaps start from 500sat?)
* Consider making the "Donate now" button an actual Wizard button so it appears on the bottom row next to Apply - it would be more pleasing to the eye and may be more likely to get a "curiosity" click. 
* The "Donate now" button could also have reduced text "Donate" and probably won't need an ellipsis since users will expect the chance to cancel out of the send process.

**Comment by jim618** [comment]
I've finished off this issue with:
+ some layout tweaks
+ refactored out a Sliders factory class
+ two FEST tests to check the slider and the donate button

Ready for review and closing

**Comment by gary-rowe** [comment]
Verified working. I think we need a discussion about the default values since 3000sat seems too high to me. However that discussion is not a blocker for the issue so closing.

**Comment by jim618** [comment]
RE: the default - I suggest we try it out in real life during Beta 7 and set it accordingly.

It may well change from release to release as the fee structure changes.
The lower and upper limits may well change too.

I have put in a 'normaliser' so that the value used is always between the lower and upper limits so we can  tweak the value going forward as the fee structure for Bitcoin transactions changes.
