### ISSUE TITLE
Build fails under Windows

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#322]
User @innodonni has reported build problems on Windows.

The root issue is that NTFS doesn't like file handles to be left open before rename/delete. I could open a separate issue to that effect. 

`mvn clean install` resulted in 1 test failure to be listed:
```
BasicMatcherTest.testPayerRequestAndMatcherResponse1:105 » PayerRequest Could ...
```
After changing BasicPayer to not use a temp file with `PGPUtils.encryptFile`, the following failures were listed:
```
EncryptedFileReaderWriterTest.testEncryptDecryptSuccess:74 » EncryptedFileReaderWriter PersistentContactServiceTest.testLoadAndStore:132 » ContactsSave Could not sav... PersistentHistoryServiceTest.testLoadAndStore:119 » HistorySave Could not save... WalletServiceTest.testChangePassword:153 » IllegalState Not encrypted WalletServiceTest.testCreatePaymentRequest:119 » PaymentsSave Could not write ... TrezorWalletTest.testChangePasswordTrezorSoftWallet:420 » IllegalState Not enc... TrezorWalletTest.testCreateTrezorHardWalletFromRootNode:197 » IO Failed to del... TrezorWalletTest.testCreateTrezorSoftWalletFromSniffSeed:312 » IO Failed to de...
```
After I modified `SecureFiles.writeFile` to close file handles before rename, only the Trezor tests threw in `Wallet.saveToFile`:
```
TrezorWalletTest.testCreateTrezorHardWalletFromRootNode:197 » IO Failed to del... TrezorWalletTest.testCreateTrezorSoftWalletFromSniffSeed:312 » IO Failed to de...
```
After modifying SecureFiles.fastSecureDelete to force the mmap buffer to close the file handle (not supported by the java.nio API!), all tests passed.

Looks like [Windows builds is still an open issue for Travis CI](https://github.com/travis-ci/travis-ci/issues/216).

**Comment by gary-rowe** [comment]
I've pushed changes that fix all but the `TrezorWalletTest` on Windows. This is due to an underlying problem in the Bitcoinj  `Wallet.saveToFile` leading to the message "Failed to delete canonical wallet file for replacement with autosave" and an accompanying `IOException`.

Jim, can you take a look at what we could do to safely handle autosave events in the context of encrypt and decrypt operations?

**Comment by bitcoin-solutions** [comment]
I have managed to replicate this on our little Windows 8 netbook machine.
Log from maven:

```
Tests run: 5, Failures: 1, Errors: 2, Skipped: 0, Time elapsed: 86.985 sec <<< FAILURE! - in org.multibit.hd.core.trezor.TrezorWalletTest
testCreateTrezorHardWalletFromRootNode(org.multibit.hd.core.trezor.TrezorWalletTest)  Time elapsed: 12.854 sec  <<< ERROR!
java.io.IOException: Failed to delete canonical wallet file for replacement with autosave
        at org.bitcoinj.core.Wallet.saveToFile(Wallet.java:1171)
        at org.bitcoinj.core.Wallet.saveToFile(Wallet.java:1200)
        at org.multibit.hd.core.trezor.TrezorWalletTest.testCreateTrezorHardWalletFromRootNode(TrezorWalletTest.java:197)

testCreateTrezorSoftWalletFromSniffSeed(org.multibit.hd.core.trezor.TrezorWalletTest)  Time elapsed: 19.869 sec  <<< ERROR!
java.io.IOException: Failed to delete canonical wallet file for replacement with autosave
        at org.bitcoinj.core.Wallet.saveToFile(Wallet.java:1171)
        at org.bitcoinj.core.Wallet.saveToFile(Wallet.java:1200)
        at org.multibit.hd.core.trezor.TrezorWalletTest.testCreateTrezorSoftWalletFromSniffSeed(TrezorWalletTest.java:312)

testChangePasswordTrezorSoftWallet(org.multibit.hd.core.trezor.TrezorWalletTest)  Time elapsed: 27.435 sec  <<< FAILURE!
java.lang.AssertionError: expected:<true> but was:<false>
        at org.fest.assertions.Fail.failure(Fail.java:206)
        at org.fest.assertions.Assert.failure(Assert.java:141)
        at org.fest.assertions.BooleanAssert.isEqualTo(BooleanAssert.java:136)
        at org.fest.assertions.BooleanAssert.isTrue(BooleanAssert.java:116)
        at org.multibit.hd.core.trezor.TrezorWalletTest.testChangePasswordTrezorSoftWallet(TrezorWalletTest.java:420)

SNIP

Failed tests:
  TrezorWalletTest.testChangePasswordTrezorSoftWallet:420 expected:<true> but was:<false>

Tests in error:
  TrezorWalletTest.testCreateTrezorHardWalletFromRootNode:197 + IO Failed to del...
  TrezorWalletTest.testCreateTrezorSoftWalletFromSniffSeed:312 + IO Failed to de...

Tests run: 93, Failures: 1, Errors: 2, Skipped: 1

**Comment by bitcoin-solutions** [comment]
I think the TrezorWalletTest is a bit racey, with freshKeys creating Wallet.saveNows that are done on background threads.

I have got the failures down to:
TrezorWalletTest.testChangePasswordTrezorSoftWallet
IllegalState: Not encrypted

Not sure if it is real or a test artifact yet - I don't see this on a Mac.

**Comment by bitcoin-solutions** [comment]
To exercise the wallet saving more I've put in more changes of password into the WalletServiceTest. This does wallet writes close together in time so is a good test of the wallet IO. Rather than 1 test doing 3 password changes there are now 2 tests doing a total of 8. 

I've also done similar changes to the TrezorWalletTest.

These run on a Mac - I'll also run them on our Windows machine a bit later.

**Comment by bitcoin-solutions** [comment]
A possible cause for this is contention over the wallet file. The wallet save is currently:
1) bitcoinj calls walletAutoSaveListener#beforeAutoSave
2) bitcoinj saves to temp file
3) bitcoinj renames temp file to wallet file (tries to delete wallet file on Windows)
4) walletAutoSaveListener afterAutoSave is called
5) read in the wallet file
6) encrypt it in memory
7) decrypt it in memory and check it's the same as in 5)
8) write out to a wallet.aes file
9) secure delete the wallet saved in 3)

I think 3) and 9) may be in contention sometimes.

To get round this I have put in a ReentrantLock into the WalletAutoSaveListeners.
There is an extra complication is that if the bitcoinj wallet save throws an IOException you have to make sure the lock gets released. I have put in some code so that the wallet-save lock only locks the wallet for 5 seconds max. 

Code review of MBHD WalletAutoSaveListener (and bitcoinj Wallet, though that is unchanged)

**Comment by bitcoin-solutions** [comment]
Still seeing failures on Windows due to 'java.io.IOException: Failed to delete canonical wallet file for replacement with autosave' in
TrezorWalletTest.testChangePasswordSoftWallet
TrezorWalletTest.testChangePasswordSoftWalletRepeat
TrezorWalletTest.testCreateTrezorHardWalletFromRootNode
TrezorWalletTest.testCreateTrezorSoftWalletFromSniffSeed

Note that all the MBHD soft wallet tests are running ok, even though the wallet create and password change are all very similar.

**Comment by bitcoin-solutions** [comment]
The tests are now running on the little Windows box with a combination of a rename of the wallet file before secure delete (reduces contention) and more time for the change password (which is pretty slow on the Windows test box we have).

Awaiting review (especially WalletAutoSaveListener) and closing.

**Comment by gary-rowe** [comment]
I've asked the Private Beta Group if they are able to perform builds on different Windows platforms since Travis doesn't currently support Windows. Hopefully we'll see feedback soon.

**Comment by gary-rowe** [comment]
Getting no response from the Private Beta Group so I'll see about running up some AWS instances and building on there.

**Comment by gary-rowe** [comment]
Seen/heard of successful builds on the following machines:

* Windows Vista
* Windows 7

Closing.
