### ISSUE TITLE
Cannot dismiss 'received bitcoin' alert

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#344]
This morning I noticed you cannot remove a 'received bitcoin' alert.

Error:
[2015-01-12 12:31:01,232] ERROR [safe-fixed-controller-events-1] o.m.h.c.e.ExceptionHandler - ViewEvents are expected to run on the EDT thread ! java.lang.IllegalStateException: ViewEvents are expected to run on the EDT thread
! at com.google.common.base.Preconditions.checkState(Preconditions.java:176) ~[guava-16.0.1.jar:na]
! at org.multibit.hd.ui.events.view.ViewEvents.fireAlertRemovedEvent(ViewEvents.java:207) ~[classes/:na]
! at org.multibit.hd.ui.controllers.HeaderController.onRemoveAlertEvent(HeaderController.java:167) ~[classes/:na]

**Comment by gary-rowe** [comment]
Yep, this will be part of the fallout from the #325 event refactoring. Just need to wrap it in `SwingUtilities.invokeLater()`. There will be a few of these so it would be worth extending the alert FEST test to verify the close behaviour as well as the button.

**Comment by bitcoin-solutions** [comment]
It was actually caused by the button throwing a controller event and HeaderView not subscribing to those, so I have added the subscribe to the AbstractView. Testing now

**Comment by bitcoin-solutions** [comment]
Fixed.
Awaiting review and closing

**Comment by gary-rowe** [comment]
Hmm, should a View be listening for Controller events? 

One of the reasons I split these up was to avoid these kind of issues. There is the exceptional case where `MainController` has to listen for a wizard close in order to manage handovers but perhaps the alert event would be better as a ViewEvent instead.

What do you think?

**Comment by bitcoin-solutions** [comment]
Dependency wise it is reasonable for a controller to emit a 'there is a new alert' event.
Hence it should be a controller event rather than a view event. Views depend on controllers, not the other way round.

**Comment by gary-rowe** [comment]
I agree with your reasoning that Views depend on Controllers not the other way round. However, this makes the semantics of the (non-Core) events as follows:

*Controllers work with `ControllerEvents` 
* Views work with `ViewEvents`
* Controllers can emit `ViewEvents` in order to get Views to do something on the UI (using the EDT guarantee)
* Controllers can also emit `ControllerEvents` to get other Controllers to do work asynchronously (using the non-EDT guarantee). 
* Views should not emit `ControllerEvents` directly.

It may be that the `AlertEvent` is incorrectly categorised as a `ControllerEvent` (I had to move one out of the `ControllerEvents` factory during the refactor as it was actually a `ViewEvent`).

Overall, we want to be strict about this or it'll bite us later.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
