### ISSUE TITLE
Trezor not being recognised on windows 8

### ISSUE THREAD

**Issue by bitcoin-solutions** [bitcoin-solutions/multibit-hd#379]
On the Windows 8 test machine (a little Acer netbook) a trezor is not being recognised when plugged in.
Something is happening though, when it is pulled out MBHD is showing an alert 'Trezor failed'.

Needs logging enabled before tracking this down.

**Comment by gary-rowe** [comment]
The recent commits to #378 should allow this to proceed at a basic level but I'll mark it as awaiting issue as a formality.

**Comment by gary-rowe** [comment]
I suspect I know what is happening here but would you mind posting some logging info so I can be sure.

**Comment by gary-rowe** [comment]
Received by email and corroborates the theory. I need to make a fix to the hid4java library.

**Comment by gary-rowe** [comment]
Latest hid4java on develop covers various important fixes but I noticed an occasional glitching during complex operations leading to a failed session which requires investigation.

**Comment by gary-rowe** [comment]
Verified working on Windows 8.1 64-bit.

Ready for review and close.

**Comment by gary-rowe** [comment]
Uncovered a further problem with hid4java where the device would occasionally detach and re-attach on Windows. This has been fixed in hid4java-0.3.1 which is present in multibit-hardware-0.2.1. This version of MultiBit Hardware also contains a fix for continuous reading of a USB device after it has been detached.

Given that this is now working on Windows 8 I'll close this.
