### ISSUE TITLE
Create 0.0.6 Beta 6 installer

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#397]
Once all Public Beta 6 issues are out of the way the installer can be created and pushed to the main website.

Please refer to the release procedures in the installer repo for details.

**Comment by gary-rowe** [comment]
Ready for release.

**Comment by bitcoin-solutions** [comment]
Release checklist progress so far:
1. Ensure all issues are completed for milestone. All except intermittent verifyCreateTrezorHardwareWallet_ColdStart FEST test running ok. Acceptable.
1. Update SPV checkpoints file. Last updated 4th Feb 2015 so not changed.
1. Update the local help. Updated 11th Feb.
1. Update the localisation files from crowdin.com. Updated 11th Feb.
1. Merge from `develop` into `master`, tag code. bitcoinj-alice tag=“mbhd-0.0.6beta”. multibit-hardware = v0.3.0
1. Final verification that functional tests (FEST, stress and emulator) run correctly. JUnit ok. All FEST tests except verifyCreateTrezorHardwareWallet_ColdStart run ok.
1. Final verification that latest hardware wallet firmware is supported. Trezor running 1.3.0 firmware sends ok. 
1. Create and sign installer using Windows and Apple developer keys. Done.
1. Create and check PGP signatures for binaries. Done
1. Create and check SHA256 files for binaries. Done
1. Create release note with SHA256 hashs of the binaries, Bitcoin signed by the MultiBit donation address
1. Verify the release note with earlier version of MultiBit HD. Done
1. Push to website following the directory naming conventions (expect Reddit notification from this point). Done
1. Download installers from website and smoketest on each operating system. Smoketest on Mac ok. Smoketest on Windows 8 ok.
1. Update the beta website code and blog to reflect the new version. Done
1. Push the beta website code. Done.
1. Issue a Private Beta Group notification. Done
1. Wait 24 hours for feedback (if any)
1. Push to `releases/multibit-hd/upgrade.xml` so that auto updates start
1. Issue general notification on social media Reddit/Twitter/BitcoinTalk if not already in place

**Comment by gary-rowe** [comment]
Installer released and verified working. 

Ready to push the `upgrade.xml` to both `multibit-hd/0.0.5beta` (as a one-off to fix incorrect configuration in Beta 5 installer) and `multibit-hd` for ongoing installer checks.

**Comment by bitcoin-solutions** [comment]
I've copied the updates.xml to both multibit-hd and multibit-hd/multibit-hd-0.0.5beta but don't see 0.0.5beta updating when I open it.

Try it out.

**Comment by bitcoin-solutions** [comment]
I think it's a red herring causing by me misreading the installer configuration. Looking at the installers I see both Beta 5 and Beta 6 use https://www.multibit.org/releases/multibit-hd/updates.xml as their basis. 

Note the name change from `upgrade.xml` to `updates.xml` which is a documentation error. I'll update the README in the installers accordingly. 

Can you rename and push the change?

**Comment by bitcoin-solutions** [comment]
https://www.multibit.org/releases/multibit-hd/updates.xml is the file that I updated and points to beta 6

**Comment by gary-rowe** [comment]
All work completed.

Closing,.
