### ISSUE TITLE
Receiving Addresses should be ok with no amount set

### ISSUE THREAD

**Issue by icholas** [bitcoin-solutions/multibit-hd#434]
When multiple receiving addresses have been generated, where in Multibit HD can you see the list of generated addresses?

Thanks

**Comment by gary-rowe** [comment]
These should appear in the Payments screen as unpaid payment requests. Double click an entry to examine it in more detail.

**Comment by icholas** [comment]
They only appear on the payment screen if a value/amount has been set on the request screen. If you click request and just copy the address and click finish, nothing will appear on the payment screen until someone has sent money to that address.

**Comment by gary-rowe** [comment]
Yes, the Payments screen doesn't match the use case of "Just send me something whenever to this address". The act of opening the Request panel will increment the address index (hence no Cancel button) but the actual generated address will be "lost". 

I think that an empty payment entry should be made to cover this situation which the user can then delete if they know that the request was created in error and never used to avoid clutter. 

Of course, if someone deletes the request and subsequently receives funds on it then it'll show up as normal.

Jim - one for Beta 8?

**Comment by icholas** [comment]
I agree with you Gary.

**Comment by jim618** [comment]
Propose we do the following:
+ If user does not type in an amount the Request is generated with Amount blank and it appears in the Payments table. (It can then be inspected, deleted etc)
+ Exchange rate is stored in the Payment Request (useful for tax reporting as the basis)
+ The amount is semantically considered to be 'absent/ zero'. Thus any payment into this address will reconcile it, moving it out of the Payments screen and into the appropriate receive as a matchin payment request. Thus you will never see a 'part paid' request when the amount is missing.

Propose we put it in Beta 8.

**Comment by jim618** [comment]
I've updated the code so that now if you don't add an amount in a PaymentRequest you see it in both the Payments table and in the Send/ Request screen. It appears with a BTC amount of 0. The fiat exchange rate is stored but nothing is shown in the fiat column in the table - too many zeroes otherwise.

When you pay any amount to that address it gets marked as paid and reconciles like any other payment request.

Screenshots:

![screen shot 2015-04-22 at 12 05 30](https://cloud.githubusercontent.com/assets/919427/7274092/bad628da-e8f1-11e4-92e1-335ffce626f4.png)

![screen shot 2015-04-22 at 12 05 47](https://cloud.githubusercontent.com/assets/919427/7274102/c729b796-e8f1-11e4-93c7-0c5bbd2af9b6.png)

Awaiting review and closing

**Comment by gary-rowe** [comment]
Looks good to me. Code review is fine.

Paging @icholas to chime in on this before closing.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
