### ISSUE TITLE
Restarting Multibit with previously connected Trezor hangs until timeout

### ISSUE THREAD

**Issue by tl121** [bitcoin-solutions/multibit-hd#450]
1. connect Trezor
2. start Multibit HD beta 7  (64 bit Windows exe, running on Windows 7)
3.  wait for wallet to synchronize
4. Exit Multibit
5. start Multibit 
6. nothing happens for some time. After about 40 seconds the unlock Trezor window appears.
6a.  If one is impatient one can short cut the timeout by disconnecting and reconnecting the Trezor

This is a cosmetic user interface issue, possibly protocol related.

**Comment by gary-rowe** [comment]
Yes this is a known issue with the low level USB handling. If MultiBit HD does not shut down correctly it may fail to release the USB connection resulting in a 20s delay in handling commands due to data contention. A failed shutdown would normally be associated with killing a process rather than using the Exit button/Window close button. 

Unfortunately there is no way to fix this other than instructing the user to detach/attach the device as you have discovered.

Alternatively, if you have experienced this during a normal exit cycle (click Exit, wait a few seconds while cleanup occurs, restart) then we will need to investigate further.

**Comment by tl121** [comment]
As far as I know, I used the normal exit cycle, but I will retry the experiment to verify this, since I could have made a mistake. I will try and get back to you later today.

Incidentally, if it is not a big deal, it would be good to pop up a Multi-bit window of some sort immediately when the program is launched, before attempting connections. If it had worked this way then I would probably have waited patiently (or just unplugged the Trezor to see what happens).  Other Trezor software implementations seem to work this way.

**Comment by gary-rowe** [comment]
Do you mean a splash screen? If so then we've just completed adding that for Beta 8. See #382. The behaviour from Beta 8 onwards should be:

* launch (double click icon/Bitcoin URI/payment request file)
* observe splash within 2 seconds
* observe credentials screen within 10 seconds (Trezor/password mode depending on what's plugged in)

Thanks for the feedback :-)

**Comment by tl121** [comment]
Yes, a splash screen with a progress bar would do the trick.

**Comment by gary-rowe** [comment]
Closing since Beta 8 has been out for a while with splash screen.
