### ISSUE TITLE
Add BIP70 PaymentRequest to MBHD Payments persistence

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#452]
At present once the PaymentRequest has been received it is generally lost. The correct handling is as follows:

* user sees the PaymentRequest in an alert (various ways of achieving this)
* if the user proceeds the PaymentRequest is added to the Payments persistent repository (with any local currency values noted at this point) - the original binary PaymentRequest is referenced and stored without modification within the Payments repository
* the user sees the "send bitcoin" wizard with PaymentRequest details showing
* if the user proceeds to a successful payment and a PaymentACK is received then the Payments screen will reflect the "paid" status
* failure to proceed or to receive a PaymentACK will leave the PaymentRequest "unpaid" - the user is free to delete it (and the linked PaymentRequest binary by association)

**Comment by jim618** [comment]
Some notes on the implementation of this:
+ Main point to persist the payment request is in the handler for the 'Next' press on the screen showing the Payment Request details. By clicking Next on this screen the user is indicating that this is an 'interesting' payment request that they want to track the lifecycle of. They may then cancel the actual payment (don't want to pay now, not enough funds etc) but even if they do they want the payment request itself to exist (perhaps to pay later).
+ If they click 'Cancel' on the Payment Request details screen then the Payment Request won't be saved due to lack of user interest. (??? Or store it so user has to go to Payments and do a 'Delete request ???)

@gary-rowe Is PaymentSession the primary object that needs persisting?

It is a bit confusing using PaymentRequest for both the BIP70 objects and 'our' MBHD requests created by the user from the Request button. As we are stuck with the protos I suggest we rename 'our' requests to something different. Just a prefix - say MultiBitPaymentRequest or 'UserPaymentRequest' ???

**Comment by gary-rowe** [comment]
I suggest a rename of our `PaymentRequest` to `MBHDPaymentRequest`. This keeps it line with `MBHDPaymentsProtos`. The `MBHDPaymentRequest` should be built using information provided in the `PaymentSessionSummary` and suitable exchange rates for local currency conversion. 

Only the `PaymentRequest` should need to be persisted because it contains all the information needed to construct the `PaymentSession` at a later time. This should be stored "as-is" within the encrypted Payments database and a relative link (`String`) provided to locate it later from the `MBHDPaymentRequest`. We don't need a URI `file://` since that would be absolute and may not surive a cold restore operation.

**Comment by jim618** [comment]
Sounds like a good plan going forward. I'll work on this tomorrow (Thurs).

**Comment by jim618** [comment]
I've just pushed an initial 'sketch' of the PaymentRequest support into WalletService.
It is similar to Contact/ History etc.
At the moment it does not actually persist the data - it just stores it in memory at the moment.

The old PaymentRequest has been renamed MBHDPaymentRequest

I have made a wrapper object PaymentRequestData that has the PaymentRequest and a transaction hash (of the tx that was sent to pay the PaymentRequest) and a UUID (will be used as the file name of the persisted PaymentRequest and will also be put in the SendWizardModel to tie the PaymentRequest shown to the user to the tx sent. Kind of a foreign key.)

**Comment by jim618** [comment]
The PaymentRequestData will probably need to store a FiatPayment too

**Comment by jim618** [comment]
Quite a chunk of code has gone in today so that:
+ BIP70 Payment requests get remembered (in memory only, not persisted yet)
+ UUID and tx hash are present to link tx and BIP70 request for drill down / reconciliation.
+ I'll use the UUID as the name of the file where the BIP70 payment request file gets persisted
+ BIP70 payment requests appear in the payments list in MBHD
+ You can double click on a BIP70 payment request and get a details screen.

I haven't put the fiat equivalent on the initial screen as it will be confusing as that screen is 'the offer'. It is in the data, on the payments screen and on the drill down.

Not done yet:
+ No persistence
+ No reconciliation/ status
+ Trusted status etc not done
+ No ability to pay an unpaid BIP70 payment requests
+ Cannot delete / undo delete
+ Not exported

I've been trying it with the program parameter:
file:///Users/jim/IdeaProjects/multibit-hd/mbhd-core/src/test/resources/fixtures/payments/localhost-signed.bitcoinpaymentrequest
It appears in the payment list at 26th February so you have to scroll down but 'real' BIP70 payment requests will appear at the top.

**Comment by jim618** [comment]
Just pushed some code that gives us the workflow for the BIP70 payment requests.

1) A request comes in - user sees alert in header. If they pick 'Yes' request gets saved (to memory at the moment) and user sees 'Request details' panel. Screenshot:

![screen shot 2015-03-15 at 15 59 29](https://cloud.githubusercontent.com/assets/919427/6656766/5e8a4af8-cb2c-11e4-8b63-185ddbf6eb34.png)

2) User can pay then by clicking the 'Pay this payment request'. Traverses to Send confirm screen.

3) If they dismiss this screen they can select the 'They requested' entry in the Payments list. Double click to get the same screen.

4) Once they have paid it the payment request remembers the paying tx hash. Payment request disappears as a 'primary' object from payments list.

5) If user double clicks on the tx that paid, they get a screen - after tx details - with the payment request details. Screenshot: (no pay button as it is already paid).

![screen shot 2015-03-15 at 15 47 54](https://cloud.githubusercontent.com/assets/919427/6656765/58b0d53e-cb2c-11e4-852d-a5d007eafcc4.png)

Payment request appears in the Send / Request screen under 'Send' with type: 'They requested'.

Still to do:

+ Clear tx if tx is not in wallet (after a failed send user may do a 'Repair wallet'. Needs to pay again.)

+ No persistence

+ Cannot delete / undo delete

+ Not exported

+ Disable 'Pay this payment request' button if sync is not finished.

**Comment by jim618** [comment]
I've spawned new issues for everything except persisting the BIP70 payment requests to stop this issue becoming a monster one

**Comment by jim618** [comment]
I've pushed code that persists the PaymentRequests.
You can save a payment request, close down MBHD, restart it and then pay it.

The trust information is not being stored though - I store the identity directly in the PaymentRequestData but not the trust status at the moment.

I think the trust loader/ identity verification needs a bit of work to make it solid generally.

Anyhow, awaiting review and closing.

I have split off the other bip70 items into separate issues for clarity

**Comment by gary-rowe** [comment]
Verified working.

Closing.
