### ISSUE TITLE
Disable "Yes" button on alert until sync has completed for BIP21 payment request

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#472]
This is to harmonise the behaviour of BIP21 and BIP72 so that when synchronisation is ongoing the BIP21 payment cannot be completed (Next button disabled).

**Comment by jim618** [comment]
I've pushed code that enables/ disables the 'Next' button on the SendBitcoinEnterAmount' view.
You have to test it using a command line parameter at the moment because #445 is stopping bitcoinURI clicks coming in from websites.

The idea of this change is that the alert is always actionable but when you get onto the enter amount screen you have to wait until any sync completes. The tx preparation where it picks the tx outputs to spend are driven by the 'Next' button so this is the place to put it.

Screen of button disabled on sync:
![screen shot 2015-03-21 at 12 12 10](https://cloud.githubusercontent.com/assets/919427/6764985/d5ea7e8c-cfc4-11e4-8c10-2da763465ef9.png)

Then enabled once sync completes:
![screen shot 2015-03-21 at 12 13 16](https://cloud.githubusercontent.com/assets/919427/6764986/db88a1a2-cfc4-11e4-9ab7-44527aed7468.png)

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working.

Closing.
