### ISSUE TITLE
Native-looking UI controls

### ISSUE THREAD

**Issue by thousandsofthem** [bitcoin-solutions/multibit-hd#506]
Is there any way to make controls (buttons etc) look like native ones? 
Electrum does that e.g.
Current controls basically ruins impression of overly solid (and handy) product

**Comment by gary-rowe** [comment]
We did look into this at the very early design stages (the [project README](https://github.com/bitcoin-solutions/multibit-hd/blob/develop/README.md) provides details) but had to reject this approach because of its limitations. When MultiBit HD was started Java8 + JavaFX was not mature enough to handle all the internationalisation issues of our user base (no RTL support, no native integration for Bitcoin URI handling, no reporting uncaught exceptions etc).

Further, the Swing framework is near bulletproof for most use cases and can be made to look reasonably modern. Within the confines of Swing choosing a native platform Look and Feel (LaF) meant tripling the amount of custom code required to support certain UI effects such as colouring buttons or applying transparency so we opted for the generic Nimbus LaF.

We experimented with a "flat" look but that really didn't look right at all so what we've ended up with is a reasonable compromise.

Are there any particular controls that are causing problems for you?

**Comment by thousandsofthem** [comment]
Okay, thanks for the answer!

1)
> Are there any particular controls that are causing problems for you?

No problems mostly, except maybe unreadable "disabled" buttons: 

![monosnap 2015-04-14 14-39-15](https://cloud.githubusercontent.com/assets/736279/7135909/18a8cc68-e2b4-11e4-995d-3367b847d168.png)

2) 
> We experimented with a "flat" look but that really didn't look right at all so what we've ended up with is a reasonable compromise.

At this moment latest beta supports three visual styles (these styles do not alter dropdown lists, most of buttons etc) and only one of them imo is "ok" - "Lite theme" one. Just checked it one more time and now i can say why so: "Dark" and "Bootstrap" both using gradients everywhere (and gradients never looked ok, nor windows95, nor Windows7, 8, 10, nor OSX nor every other OS).
"Lite" is kind-of-good one, because most of the buttons are now gradient-free.
Example:
![monosnap 2015-04-14 14-47-02](https://cloud.githubusercontent.com/assets/736279/7136038/384d1046-e2b5-11e4-938c-25a66bd58d8a.png)

Also, on screenshot  1 buttons 1 and 2 are ok and 3 is gradiented one. I hope that inconsistency can be fixed easily which, in turn (i hope), will change overall impression from the UI to be more solid and consistent. Makes sense?

3) About controls itself. With buttons fixed (mostly), most common control remain is dropdown list ("select"). I hope simple color/style tuning can make it look matching rest of the UI without drastic internal changes

**Comment by gary-rowe** [comment]
Thanks for providing more detail - very helpful.

I'm inclined to agree with you on the use of the gradients within the buttons and on the difficulty of reading the default buttons when disabled. I think it would be a fairly minor piece of work to modify the Nimbus LaF painters to reduce the contrast of the gradients. 

Working with the Swing "default" buttons (such as the "Exit" button above) is a point of pain due to the difficulty of configuring the button painters in the "default" mode. You'd think it'd be trivial but it's really not.

I'm a little confused about your comments on the dropdown list. Could you provide examples like you have for the buttons with more details on the difficulties you're encountering?

**Comment by thousandsofthem** [comment]
dropdown list - not really difficulties, just weird look'n'feel

![monosnap 2015-04-14 16-59-39](https://cloud.githubusercontent.com/assets/736279/7138315/36991ae8-e2c8-11e4-97f6-e71428720db4.png)
![monosnap 2015-04-14 17-00-52](https://cloud.githubusercontent.com/assets/736279/7138316/36a1a5b4-e2c8-11e4-9116-5cf3ac5e37cf.png)

**Comment by gary-rowe** [comment]
Yeah, the Swing JComboBox is a bit strange and this was the best compromise I could reach. 

For editing, a bordered text field was required to allow data entry with similar visual cues to the other text fields. The dropdown list selector was left as "read only blue" simply to match the dropdown lists used elsewhere (such as the language selector shown).

I'll take another look at the colouring for the dropdown button on this control. It might be an easy fix.

**Comment by thousandsofthem** [comment]
thanks!

**Comment by gary-rowe** [comment]
Some button work. I've made them linear (no gradient) throughout:
![screen shot 2015-04-15 at 23 33 37](https://cloud.githubusercontent.com/assets/342133/7170641/eb88ab76-e3c7-11e4-96ab-d1a4c89a526e.png)

And added support for a coloured default button:
![screen shot 2015-04-15 at 23 33 50](https://cloud.githubusercontent.com/assets/342133/7170644/f0cd2846-e3c7-11e4-8743-9a0e5f125c4a.png)

I've also experimented with changing the colour for the default button to be green:
![screen shot 2015-04-15 at 23 37 51](https://cloud.githubusercontent.com/assets/342133/7170708/7387fc98-e3c8-11e4-94fe-26267af14ad1.png)

I'm not convinced on the rendering of the default buttons. It's very fiddly under the covers and the end result isn't quite right.

**Comment by thousandsofthem** [comment]
> I'm not convinced on the rendering of the default buttons.

Yeah, something feels off. Still, overall feeling drastically changed, like "modern app" vs "old-fashioned app". That flat-ty feeling. dunno?

**Comment by gary-rowe** [comment]
OK, I've fixed up the default controls. I've left the default button as green for now (thoughts anyone?). 

Here's the new look default button in the Bootstrap theme (initially disabled with slightly improved contrast, then enabled):

![screen shot 2015-04-16 at 23 16 18](https://cloud.githubusercontent.com/assets/342133/7192621/22016702-e48f-11e4-9794-dd2f4ae32b1a.png)
![screen shot 2015-04-16 at 23 16 34](https://cloud.githubusercontent.com/assets/342133/7192622/2208e86a-e48f-11e4-9248-6031491f0dbc.png)

And in the Dark theme:

![screen shot 2015-04-16 at 23 17 48](https://cloud.githubusercontent.com/assets/342133/7192620/21f8e780-e48f-11e4-84b8-0000125b89b9.png)

I'm pretty happy with the overall result now so this is ready for review and close.

**Comment by thousandsofthem** [comment]
:+1:

**Comment by jim618** [comment]
Looks good Gary

**Comment by jim618** [comment]
Everything looks better without the gradient but the legibility of the regaulr buttons is poor with the dark theme. See screen shot. The color is black on dark grey - no contrast.

![screen shot 2015-04-17 at 13 52 54](https://cloud.githubusercontent.com/assets/919427/7202325/33e98b1e-e509-11e4-8855-ff12ca0e6a46.png)

**Comment by gary-rowe** [comment]
Agreed. Also I noticed earlier that the Switch in Exit/Switch is low contrast in Dark theme too. 

More fiddling required (and I'll have a look at flattening the drop down list button in as well)

**Comment by jim618** [comment]
Also, the bottom right buttons (Finish, etc) give the user no feedback if you click them, or press enter to activate them.

**Comment by gary-rowe** [comment]
Improved button contrast and mouse over colour change.
Here's the help screen with the "Home" icon having a mouse over (slightly darker):
![screen shot 2015-04-17 at 22 58 08](https://cloud.githubusercontent.com/assets/342133/7211739/140416f0-e556-11e4-922b-c9b1d94968ec.png)

Same screen in Dark theme (no mouse over just showing contrast in buttons):
![screen shot 2015-04-17 at 21 41 50](https://cloud.githubusercontent.com/assets/342133/7211752/31a91728-e556-11e4-81bc-1234bfdcff96.png)

If you're happy with the improved mouse over, Jim, I'll proceed to the flatter drop down.

**Comment by gary-rowe** [comment]
I've taken a look at flattening the ComboBox arrow button but it's going to be tricky (full day of effort at least) so I'm going to defer that to a later release. 

Ready for review and close (button behaviour only).

**Comment by jim618** [comment]
Yes that all looks good. Tried all three themes and there is:
+ better definition on mouse over
+ feedback on buttonPressed.

Looks much nicer. Closing

**Comment by jim618** [comment]
I've reopened this one as the 'Finish' button on the Wallet start up gives no feedback when it is clicked.
As this will be used by everyone on every wallet start I think it should be responsive to clicking/ enter press

**Comment by gary-rowe** [comment]
This is probably because it's already got the focus as well as being the default. If you mouse over it becomes a touch darker and if you change focus then it loses its border. 

I've adjusted it so that it doesn't have default focus in the same way as the Unlock panel view. This should give a bit of feedback.

Ready for review and close.

**Comment by jim618** [comment]
Yup get nice focus / click feedback now.
Closing
