### ISSUE TITLE
Improve wallet creation report screen with "Your wallet is ready" message

### ISSUE THREAD

**Issue by gary-rowe** [bitcoin-solutions/multibit-hd#512]
User feedback from @crwatkins has indicated that the current wallet report screen would benefit from a message along the lines of:

"Your wallet has been created and locked successfully. Click Finish to show the unlock screen."

This is to overcome the jarring nature of the unexpected appearance of the Unlock screen.

**Comment by jim618** [comment]
Agreed

**Comment by jim618** [comment]
I've added in text to make the segue less jarring at the end of the wallet create.
Rather than using 'unlock', which we only use on the button, I have refered to the password entry screen directly.

Screenshot:
![screen shot 2015-04-21 at 17 23 46](https://cloud.githubusercontent.com/assets/919427/7257161/73b7ea48-e84b-11e4-89ff-6a42d1a25a5e.png)

The similar label for Trezor wallet creation has been changed to:
Your Trezor wallet is now ready to use. Press "Finish" to show the PIN entry screen

**Comment by gary-rowe** [comment]
Looks good to me.

**Comment by crwatkins** [comment]
Good.

**Comment by gary-rowe** [comment]
Closing.
