### ISSUE TITLE
Cannot create Trezor wallet from wiped device

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#534]
Just tried wiping a device in MBHD and then creating a new Trezor wallet.
Crash reporter gave:

```
o.m.h.u.v.w.AbstractHardwareWalletWizard - Wizard panel name CREDENTIALS_REQUEST_MASTER_PUBLIC_KEY 
[2015-04-21 16:34:58,045] ERROR [AWT-EventQueue-1] o.m.h.c.e.ExceptionHandler - Uncaught exception ! java.lang.IllegalStateException: Unexpected button: WIPE_DEVICE
! at org.multibit.hd.ui.views.wizards.credentials.CredentialsWizardModel.showButtonPress(CredentialsWizardModel.java:200) ~[classes/:na]
! at org.multibit.hd.ui.views.wizards.AbstractHardwareWalletWizard$7.run(AbstractHardwareWalletWizard.java:259) ~[classes/:na]

**Comment by jim618** [comment]
@gary-rowe I had a go at this but I can feel that I am messing up the state transitions in CredentialsWizardModel which will probably be trouble than its worth. Can I ask you to have a look at it please ?

Specifically the failure path is when you DON'T plug in the wiped Trezor before starting MBHD, you plug it in on the 'Enter credentials' screen.

**Comment by jim618** [comment]
Note that if you have your wiped Trezor plugged in BEFORE starting MBHD and do a 'Create wallet' it all works fine.

**Comment by gary-rowe** [comment]
OK. The FEST tests (Cold Start) should give a good insight into the expected messages and state transitions coming from the device. That said, I don't think we have one where it gets inserted at Credentials so I'll take it on.

**Comment by jim618** [comment]
okey dokey

It could have been broken for a while actually and we didn't notice. It only appears if you plug it in on the Credentials screen AND have a wiped Trezor

**Comment by gary-rowe** [comment]
The problem was with how the Credentials wizard communicated the handover to the Welcome wizard. Previously it relied on a wizard close event which was picked up by `MainController`. This didn't actually close the Credentials wizard leaving it open to receive ongoing events, including hardware events. Consequently a horrible mix of state changes occurred (imagine 2 client FSMs against a single Trezor - shudder). 

I've fixed it now so that when a wiped Trezor is detected the Next button is enabled on the master public key request page. The Next button uses the Finish button action so it can properly close itself.

Ready for review and close.

**Comment by jim618** [comment]
This all works fine now. Tried a freshly wiped Trezor plugged in on the Credentials password screen and successfully completed the Create Trezor wallet wizard.

Closing.
