### ISSUE TITLE
Restore of soft wallet completed ok but in report page there is a 'x' against wallet created

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#577]
I just did a restore of a BIP32 soft wallet from a zip backup.
It all worked fine but in the wallet restore report screen there was a X against the 'wallet created ok' message. It did not go away when the wallet synced and there were no errors in the log.

**Comment by jim618** [comment]
I think I have also seen this in the FEST tests, en passant

**Comment by jim618** [comment]
Screenshot:

![screen shot 2015-05-25 at 13 20 45](https://cloud.githubusercontent.com/assets/919427/7797239/435fca04-02e1-11e5-89f7-d3213d443dd7.png)

**Comment by jim618** [comment]
Also, it is misleading to have a 'Press finish to show the wallet screen' for this usage of Wallet created successfully. Label usage needs splitting into two terms

**Comment by gary-rowe** [comment]
Adjusted the return value in `RestoreWalletReportPanelView` to be `true` if the wallet is present, rather than depending on the Bitcoin network starting. Duplicated this logic into the Trezor restore.

This screen shot shows it working (previously it showed a cross):

![screen shot 2015-05-29 at 21 51 44](https://cloud.githubusercontent.com/assets/342133/7892577/7f16c56a-064d-11e5-9485-0f8cbbca460d.png)

Ready for review and close.

**Comment by jim618** [comment]
Tried it out with a couple of sets of wallet words.
Worked fine.
Closing
