### ISSUE TITLE
contribute to MultibitHD interface design and usability check

### ISSUE THREAD

**Issue by netcaster** [bitcoin-solutions/multibit-hd#621]
Hi Owner

i am looking to contribute a new deisgn for the new edition

there is alot i can do in term of design and usability 

as a start can you please let me know how the themes are build for this software ? i will send a new theme draft to check quality and continue from there 

appreciate if you guide me as i am new here

thanks
M.Ezzdin

**Comment by gary-rowe** [comment]
Hi @netcaster and thank you for the offer of assistance.

In order to make progress with the themes you'll need to have reasonably in-depth knowledge of Java Swing and the Nimbus LookAndFeel in particular. There's no CSS or HTML styling like in JavaFX.

You'll probably want to start by just making an extra colour theme (we currently have Bootstrap, Light and Dark). You can do this by looking at the `Themes` and `ThemeKey` classes (see `mbhd-swing` module) and then adding your own. I'd recommend making changes in the Intellij IDE (a free community edition is available and instructions for using it are in the [MultiBit HD wiki](https://github.com/bitcoin-solutions/multibit-hd/wiki/How-to-build-the-project-with-Intellij)).

As regards introducing more complex behaviour such as a "Flat" or "Aqua" theme then you'll be wading into some complex Java LookAndFeel work which may be a lot more effort than you first envisage. For an example of this kind of fiddly work, take a look at the `NimbusDecorator` factory class which provides much of the button colouring code.

**Comment by gary-rowe** [comment]
I'll add this issue to the Support milestone for now and as things progress we can see about a release milestone.

**Comment by gary-rowe** [comment]
A couple of considerations for a theme that would be useful are:

* improved integration with the underlying operating system colour schemes and accessibility options
* themes to assist colour blind users
* themes with larger font sizes

**Comment by gary-rowe** [comment]
Closed due to inactivity.
