### ISSUE TITLE
Rearrange start up order to show splash screen earlier, use hardware time better

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#637]
Hi Gary,
I have pushed a couple of commits that:
+ move showing the splash screen to before the initialise core
+ move the GenericApplication setup to inside the 2000 millisecond 'hardware sleep period'

This shows the splash a bitter earlier and I noticed the GenericApplication _can_ take 900 ms on my machine (but only sometimes).

On my machine the best startup I get is: I see the splash screen at 3 to 4 seconds. See the password screen at 7 to 8 seconds.

Please review the change and close if you are happy with it.

edit: It is just one commit (18e72c4)

**Comment by gary-rowe** [comment]
Looks good overall. I replaced the configuration loading back under the logging bootstrap due to its inclusion within the Bitcoin URI processing that the listening service may perform. When I was first optimising the start up sequence I had some issues with configurations not being in place early enough.

If you're happy to close after this change then so am I.

**Comment by jim618** [comment]
Checked operation both with and without Trezor successfully.
Nice time save to check if Trezor is present. Most startups won't have a Trezor attached.
