### ISSUE TITLE
First time MBHD starts up each day the splash screen is blank

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#646]
The first time MBHD starts up each day on my Mac the splash screen is blank gray. There is no image.
Subsequent start ups it renders ok.

**Comment by gary-rowe** [comment]
Looking over the code in `MultiBitHD.java` line 112 it appears that the AWT splash screen is getting launched within a Swing EDT thread. This is incorrect. The splash screen is deliberately outside of Swing so that it will render using AWT's heavyweight components while the Nimbus LaF is still loading in the background. This gives a faster time to show.

I've removed the EDT code and added a very short `Thread.sleep()` to allow AWT time to render the splash screen image. This should give reliable splash screen rendering.

I'm unsure of why the EDT wrapping was introduced - it might have been in response to FEST tests moaning about EDT requirements. Can you verify this?

Ready for review and close.

**Comment by jim618** [comment]
I've built an installer with the updated code and tried it several times, including straight from a reboot.
Eah time the splash screen rendered correctly.

I am not sure why it was added to the Swing EDT - over zealous SwingUtilities wrapping probably.
