### ISSUE TITLE
Unconfirmed transactions occurring a lot recently

### ISSUE THREAD

**Issue by tfr0404** [bitcoin-solutions/multibit-hd#655]
This has now happened with my previous 3 sends of around $650 in coin. The receiving party tells me they have succesfully been notified of the incoming coin, but it remains unspendable.  The incoming is no problem. Just outgoing seems to have an issue. Ive sent more than 20 BTC with multibit in the past 45 days problem free. This is the first issue Ive encountered and its concerning. This all started today btw.

Honestly, Im not 100% certain that multibit is the problem but after sending 3 separate transactions to different addresses resulting in the same thing is why I'm starting here.

Please help.

**Comment by gary-rowe** [comment]
This is due to an ongoing stress test/DoS attack occurring on the Bitcoin network. It has seen extensive coverage on the various Bitcoin forums (see our [Community](https://multibit.org/community.html) page for many links) and is causing a lot of problems for people. We recently [wrote a blog article](https://multibit.org/blog/2015/06/23/bitcoin-network-stress-test.html) covering the first wave. Essentially there are a lot of low-value high-volume transactions being submitted to the Bitcoin network which have overloaded the nodes. Consequently the miners are prioritising transactions with the highest attached fee. 

MultiBit HD (version 0.1.1 and below) allows a range of fees from 1,000 to 10,000 satoshis which used to be sufficient for the network conditions. This situation has now changed so we are introducing a wider range 1,000 to 50,000 satoshis to cover the new conditions in [0.1.2](https://github.com/bitcoin-solutions/multibit-hd/milestones/Release%200.1.2). This is due to be released shortly and will trigger the usual automatic update notification.

It is difficult for us to communicate these wider network issues directly to our users due to our privacy policy so we rely on users keeping themselves informed through the Community forums. 

Since this is out of our control I will close this issue.
