### ISSUE TITLE
Improve ErrorReporter to not report known exceptions

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#708]
There are a few errors/ stack traces that are known to be benign.
Improve the error reporter so that these aren't reported to the user (and they can continue with MBHD).

**Comment by gary-rowe** [comment]
We must be judicious about including anything in the list of "benign" exceptions. In particular (and this is checked for in the `isBenign` method) the exception must not contain any `org.multibit` code. If it does then we have an opportunity to detect the failure and handle it. 

Code that lies outside of our control (e.g. originating from a paste or focus transition entirely within Swing/JDK methods) is not possible for us to detect and thus is a candidate for inclusion if all investigation draws a blank on a solution.

To verify, add a code block similar to this into `CredentialsEnterPasswordPanelView`:

```java
    if (true) {
      throw new NullPointerException("Plik");
    }
```
Note the error reporting dialog. 

For further investigation, adjust `ExceptionHandler.isBenign` to treat this as benign. Observe the corrupted UI in the wallet list due to the failed method completion. 

Ready for review and close.

**Comment by jim618** [comment]
LGTM.

Closing.
