### ISSUE TITLE
Import old wallets in Read-Only mode.

### ISSUE THREAD

**Issue by jdevora** [bitcoin-solutions/multibit-hd#714]
I'm a user of the Classic MultiBit wallet.
I don't plan to migrate because I'm not willing to "loose" my transaction history and miss future transactions sent to old addresses.

I know that your don't want to support private keys that you can't recover from the single pass phrase.

Can I suggest another option?

My suggestion is to import the keys as "Read-only" more, just for be able to see the transactions.
You could even implement a "spend at import" feature, when you import a old private key, you transfer all the BTC to a "change address" from the new wallet  and if new money arrives to an old address you could force the move to a new address or make it a priority to spend that money first (allways sending the "change" to a new address).
 
I hope this solution fits your "we don't want to be responsible of the  old keys" policy

**Comment by gary-rowe** [comment]
Hi @jdevora and thanks for your feedback. 

Adding special handling for one-off non-reproducible private keys is not something we'd like to implement. Separating the "read only" address balance from the "read/write" versions would lead to a confusing user experience.

Perhaps a better solution would be to simply maintain the old keys in MultiBit Classic, with your existing backup solution in case of problems, and then create a new wallet in HD to make use of the improvements made along the way. If you don't get on with HD, no harm done, just spend back into Classic.

At the start there would be a schism between the old and new, but they both run happily side by side. Over time it may be that HD or Classic dominates in which case your choice becomes clear - or they remain in balance depending on what needs to be done. 

As an example, I run both HD and Classic on several machines to track various situations. I find I use HD more often but Classic remains useful.

Since this issue won't get implemented I'll mark it as closed.
