### ISSUE TITLE
When creating KeepKey wallet you get a screen with 1/2 but there is no 2/2

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#748]
When you create a KeepKey wallet, on the screen on MBHD that corresponds to the wallet words being shown on the KeepKey the title say 'recovery screen 1/2'.
However the next screen is the KeepKey wallet create report. There is no 'recovery screen 2/2'

If there is no 2/2 screen then it should be removed as it is confusing and suggests that a screen somewhere is missing

**Comment by gary-rowe** [comment]
Yeah, this is a feature of their firmware. They know if their wallet words will fit on 1 or 2 screens depending on the size. We cannot know this so must use a statistical approach based on a button request. Therefore we can infer 2/2 so for consistency must present 1/2 in all cases.

It's unavoidable without a special message from the KeepKey device which would be a significant security leak since it would limit the overall size of the chosen wallet words.

If you're OK with this, feel free to close with no action required.

**Comment by jim618** [comment]
I'll close it - we don't know the actual length of the wallet words being shown.
