### ISSUE TITLE
Upgrade Should Allow Authentication on Mac OS X

### ISSUE THREAD

**Issue by dgiffin** [bitcoin-solutions/multibit-hd#770]
When I run the upgrade on Mac OS X it needs to be run as an Administrator account, would be really useful if the upgrade allowed me to authenticate as an Administrator rather than having to login in as an Administrator account to run the the upgrade.

**Comment by jim618** [comment]
I'll see if there is an option somewhere in the installer generator we use (Install4j) to automatically escalate to Administrator if you are using a non-Administrator account

**Comment by jim618** [comment]
I have 'ticked the box' in the installer project so that if you are using a non-Admin account the installer asks for the username/ password of an Administrator.

I have tested generated installer using a non-Admin account on Mac and it works fine.
It still needs testing on Win.

Awaiting review/ testing and closing

**Comment by dgiffin** [comment]
That is amazingly fast, thank you!

**Comment by jim618** [comment]
No problem.
Obviously the testing Gary and I have done have been on admin accounts and we didn't notice the lack of escalation. Thanks for the feedback

**Comment by jim618** [comment]
Tested the created Windows installer on our Win 8 test machine with a non-Administrator account. It correctly asked me for an administrator account name/ password before continuing the installation..

Awaiting review and closing.

**Comment by gary-rowe** [comment]
Verified working. Closing.
