### ISSUE TITLE
KeepKey not being recognised on Windows 8 after 1.0.4 firmware upgrade

### ISSUE THREAD

**Issue by jim618** [bitcoin-solutions/multibit-hd#852]
My KeepKey is not being recognised when plugged in on the little Win 8 box after the most recent firmware upgrade.

It works ok on Mac and gives these details:
```
org.multibit.hd.hardware.core.messages.Features@6701fb2[
  vendor=keepkey.com
  version=1.0.4
  bootloaderMode=false
  deviceId=F831D53EA74923314ECA400E
  pinProtection=true
  passphraseProtection=false
  language=english
  label=keepkey dev
  coins=[Bitcoin, Testnet, Namecoin, Litecoin, Dogecoin, Dash]
  initialized=true
  revision= 0c 1c ae 8e dc 16 ff 22 41 ae fd 65 9d 11 3c c0 d6 b6 5b 10
  bootloaderHash= 63 97 c4 46 f6 b9 00 2a 8b 15 0b f4 b9 b4 e0 bb 66 80 0e d0 99 b8 81 ca 49 70 01 39 b0 55 9f 10
  imported=false
  supported=true
]
```
Note:
+ The KeepKey also fails to be recognised in MBHD 0.1.4 on Win 8 after firmware upgrade.
+ Trezor is seen on MBHD 0.2.0 on Win 8 ok.
+ I looked through the log but didn't see anything unusual.

**Comment by gary-rowe** [comment]
Using an upgraded to latest firmware KeepKey:

* verified OS X (El Capitan)
* verified Windows 10
* verified Linux (Ubuntu 14.4)

**Comment by gary-rowe** [comment]
Further investigation with a Windows 8 machine showed that both 1.0.0 and 1.0.4 KeepKey firmware works fine with the 0.1.4 and 0.2.0 MultiBit HD code. 

The machine itself is quite dated to act as a representative example of real world use and it is possible that in the original test the USB did not detect the insertion of the device. This is a lower level than the firmware and so it is more likely that this is an intermittent fault with the test machine rather than the KeepKey.

Closing (unless feedback from users indicates an actual problem).
