### ISSUE TITLE
No option to set currency exchange rate different than USD

### ISSUE THREAD

**Issue by SMH17** [bitcoin-solutions/multibit-hd#893]
Would be useful add others currencies not only USD in the exchange rate settings.

**Comment by gary-rowe** [comment]
The currency supported is set by the exchange. For example, Bitstamp only offers USD whereas Kraken supports EUR. You can also select any national currency by the Open Exchange Rates API. There is a link to the appropriate (free) sign up page beside the drop down.

There is more information here: https://multibit.org/en/help/hd0.3/exchange-settings.html

Since this is fully supported already, I'll close this issue.
