### ISSUE TITLE
Multi-wallet management

### ISSUE THREAD

**Issue by SMH17** [bitcoin-solutions/multibit-hd#895]
A very useful feature would be the support of multiple wallet management, allowing the user to create a master account where add and labels all the Bitcoin wallets that want if needs many separate wallets for whatever reason (e.g. business wallet, home wallet etc.).

(For this purpose a nice design choice would be the use of tabbed panes where each tab is dedicated to a wallet.)

Let me know what do you think about that, so eventually if you exclude this possibility I may consider to implement this feature myself forking this project.

**Comment by gary-rowe** [comment]
Thanks for offering up your feedback.

We went down this road with MultiBit Classic and decided against it in MultiBit HD due to the complexities it introduces when synchronizing over SPV. Instead we went with the Switch Wallet capability that allows each wallet to be completely independent of the others. This simplifies synchronization and also improves security and UX. Consider the process by which a user switches between a hardware wallet and a soft wallet. In each case the process is the same.

Since this is unlikely to be implemented, I'll close this.
